/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "baja_live_comm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(GPS, GPS, AUTO)


PB_BIND(Localization, Localization, AUTO)


PB_BIND(Timestamp, Timestamp, AUTO)


PB_BIND(AnalogChannel, AnalogChannel, AUTO)


PB_BIND(Communication, Communication, AUTO)


PB_BIND(CarState, CarState, AUTO)


PB_BIND(RTKCorrection, RTKCorrection, AUTO)


PB_BIND(Observation, Observation, AUTO)


PB_BIND(LiveComm, LiveComm, AUTO)











