/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "wsg_drive_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wsg_drive_data_t, wsg_drive_data_t, 2)



