/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "wsg_pi_time.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(wsg_pi_time_t, wsg_pi_time_t, AUTO)



