/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_BAJA_LIVE_COMM_PB_H_INCLUDED
#define PB_BAJA_LIVE_COMM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _AnalogChannel_ChannelType {
    AnalogChannel_ChannelType_AXLE_TORQUE_FRONT_LEFT = 0,
    AnalogChannel_ChannelType_AXLE_TORQUE_FRONT_RIGHT = 1,
    AnalogChannel_ChannelType_AXLE_TORQUE_REAR_LEFT = 2,
    AnalogChannel_ChannelType_AXLE_TORQUE_REAR_RIGHT = 3,
    AnalogChannel_ChannelType_AXLE_RPM_FRONT_RIGHT = 4,
    AnalogChannel_ChannelType_AXLE_RPM_FRONT_LEFT = 5,
    AnalogChannel_ChannelType_AXLE_RPM_REAR = 6,
    AnalogChannel_ChannelType_SHOCK_LEN_FRONT_RIGHT = 7,
    AnalogChannel_ChannelType_SHOCK_LEN_FRONT_LEFT = 8,
    AnalogChannel_ChannelType_SHOCK_LEN_REAR_RIGHT = 9,
    AnalogChannel_ChannelType_SHOCK_LEN_REAR_LEFT = 10,
    AnalogChannel_ChannelType_STEERING_DATA = 11,
    AnalogChannel_ChannelType_TACHOMETER = 12,
    AnalogChannel_ChannelType_POWER_USE = 13,
    AnalogChannel_ChannelType_BRAKE_PRESSURE_FRONT = 14,
    AnalogChannel_ChannelType_BRAKE_PRESSURE_REAR = 15,
    AnalogChannel_ChannelType_MISCELLANEOUS = 16
} AnalogChannel_ChannelType;

typedef enum _Communication_DriverInstruction {
    Communication_DriverInstruction_STOP_IMMEDIATELY = 0,
    Communication_DriverInstruction_STOP_FOR_PIT = 1
} Communication_DriverInstruction;

typedef enum _Communication_DriverResponse {
    Communication_DriverResponse_SEND_HELP = 0,
    Communication_DriverResponse_PIT_REQUEST = 1
} Communication_DriverResponse;

typedef enum _CarState_EngineStatus {
    CarState_EngineStatus_ENGINE_NORMAL = 0,
    CarState_EngineStatus_ENGINE_IDLING = 1,
    CarState_EngineStatus_ENGINE_CHOKED = 2,
    CarState_EngineStatus_ENGINE_UNDERPERFORMING = 3,
    CarState_EngineStatus_ENGINE_OFF = 4
} CarState_EngineStatus;

/* Struct definitions */
typedef struct _GPS {
    float latitude;
    float longitude;
    float altitude;
} GPS;

typedef struct _Localization {
    float x;
    float y;
    float z;
    float roll;
    float pitch;
    float yaw;
    bool has_vx;
    float vx;
    bool has_vy;
    float vy;
    bool has_vz;
    float vz;
    bool has_wr;
    float wr;
    bool has_wp;
    float wp;
    bool has_wy;
    float wy;
} Localization;

typedef struct _Timestamp {
    uint64_t ts;
} Timestamp;

typedef struct _AnalogChannel {
    AnalogChannel_ChannelType channel_type;
    pb_callback_t encoded_analog_points;
} AnalogChannel;

typedef struct _Communication {
    bool has_instruction;
    Communication_DriverInstruction instruction;
    bool has_driver_response;
    Communication_DriverResponse driver_response;
} Communication;

typedef struct _CarState {
    bool has_engine_status;
    CarState_EngineStatus engine_status;
    bool has_rollover_status;
    bool rollover_status;
} CarState;

typedef struct _RTKCorrection {
    pb_callback_t rtk_correction;
} RTKCorrection;

typedef struct _Observation {
    bool has_timestamp;
    Timestamp timestamp;
    pb_size_t which_data;
    union {
        GPS gps;
        Localization localization;
        Communication communication;
        AnalogChannel analog_ch;
        CarState car_state;
        RTKCorrection rtk_correction;
    } data;
} Observation;

typedef struct _LiveComm {
    pb_callback_t observations;
} LiveComm;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AnalogChannel_ChannelType_MIN AnalogChannel_ChannelType_AXLE_TORQUE_FRONT_LEFT
#define _AnalogChannel_ChannelType_MAX AnalogChannel_ChannelType_MISCELLANEOUS
#define _AnalogChannel_ChannelType_ARRAYSIZE ((AnalogChannel_ChannelType)(AnalogChannel_ChannelType_MISCELLANEOUS+1))

#define _Communication_DriverInstruction_MIN Communication_DriverInstruction_STOP_IMMEDIATELY
#define _Communication_DriverInstruction_MAX Communication_DriverInstruction_STOP_FOR_PIT
#define _Communication_DriverInstruction_ARRAYSIZE ((Communication_DriverInstruction)(Communication_DriverInstruction_STOP_FOR_PIT+1))

#define _Communication_DriverResponse_MIN Communication_DriverResponse_SEND_HELP
#define _Communication_DriverResponse_MAX Communication_DriverResponse_PIT_REQUEST
#define _Communication_DriverResponse_ARRAYSIZE ((Communication_DriverResponse)(Communication_DriverResponse_PIT_REQUEST+1))

#define _CarState_EngineStatus_MIN CarState_EngineStatus_ENGINE_NORMAL
#define _CarState_EngineStatus_MAX CarState_EngineStatus_ENGINE_OFF
#define _CarState_EngineStatus_ARRAYSIZE ((CarState_EngineStatus)(CarState_EngineStatus_ENGINE_OFF+1))




#define AnalogChannel_channel_type_ENUMTYPE AnalogChannel_ChannelType

#define Communication_instruction_ENUMTYPE Communication_DriverInstruction
#define Communication_driver_response_ENUMTYPE Communication_DriverResponse

#define CarState_engine_status_ENUMTYPE CarState_EngineStatus





/* Initializer values for message structs */
#define GPS_init_default                         {0, 0, 0}
#define Localization_init_default                {0, 0, 0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define Timestamp_init_default                   {0}
#define AnalogChannel_init_default               {_AnalogChannel_ChannelType_MIN, {{NULL}, NULL}}
#define Communication_init_default               {false, _Communication_DriverInstruction_MIN, false, _Communication_DriverResponse_MIN}
#define CarState_init_default                    {false, _CarState_EngineStatus_MIN, false, 0}
#define RTKCorrection_init_default               {{{NULL}, NULL}}
#define Observation_init_default                 {false, Timestamp_init_default, 0, {GPS_init_default}}
#define LiveComm_init_default                    {{{NULL}, NULL}}
#define GPS_init_zero                            {0, 0, 0}
#define Localization_init_zero                   {0, 0, 0, 0, 0, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define Timestamp_init_zero                      {0}
#define AnalogChannel_init_zero                  {_AnalogChannel_ChannelType_MIN, {{NULL}, NULL}}
#define Communication_init_zero                  {false, _Communication_DriverInstruction_MIN, false, _Communication_DriverResponse_MIN}
#define CarState_init_zero                       {false, _CarState_EngineStatus_MIN, false, 0}
#define RTKCorrection_init_zero                  {{{NULL}, NULL}}
#define Observation_init_zero                    {false, Timestamp_init_zero, 0, {GPS_init_zero}}
#define LiveComm_init_zero                       {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define GPS_latitude_tag                         1
#define GPS_longitude_tag                        2
#define GPS_altitude_tag                         3
#define Localization_x_tag                       1
#define Localization_y_tag                       2
#define Localization_z_tag                       3
#define Localization_roll_tag                    4
#define Localization_pitch_tag                   5
#define Localization_yaw_tag                     6
#define Localization_vx_tag                      7
#define Localization_vy_tag                      8
#define Localization_vz_tag                      9
#define Localization_wr_tag                      10
#define Localization_wp_tag                      11
#define Localization_wy_tag                      12
#define Timestamp_ts_tag                         1
#define AnalogChannel_channel_type_tag           1
#define AnalogChannel_encoded_analog_points_tag  2
#define Communication_instruction_tag            1
#define Communication_driver_response_tag        2
#define CarState_engine_status_tag               1
#define CarState_rollover_status_tag             2
#define RTKCorrection_rtk_correction_tag         1
#define Observation_timestamp_tag                1
#define Observation_gps_tag                      2
#define Observation_localization_tag             3
#define Observation_communication_tag            4
#define Observation_analog_ch_tag                5
#define Observation_car_state_tag                6
#define Observation_rtk_correction_tag           7
#define LiveComm_observations_tag                1

/* Struct field encoding specification for nanopb */
#define GPS_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    latitude,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    longitude,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    altitude,          3)
#define GPS_CALLBACK NULL
#define GPS_DEFAULT NULL

#define Localization_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    x,                 1) \
X(a, STATIC,   SINGULAR, FLOAT,    y,                 2) \
X(a, STATIC,   SINGULAR, FLOAT,    z,                 3) \
X(a, STATIC,   SINGULAR, FLOAT,    roll,              4) \
X(a, STATIC,   SINGULAR, FLOAT,    pitch,             5) \
X(a, STATIC,   SINGULAR, FLOAT,    yaw,               6) \
X(a, STATIC,   OPTIONAL, FLOAT,    vx,                7) \
X(a, STATIC,   OPTIONAL, FLOAT,    vy,                8) \
X(a, STATIC,   OPTIONAL, FLOAT,    vz,                9) \
X(a, STATIC,   OPTIONAL, FLOAT,    wr,               10) \
X(a, STATIC,   OPTIONAL, FLOAT,    wp,               11) \
X(a, STATIC,   OPTIONAL, FLOAT,    wy,               12)
#define Localization_CALLBACK NULL
#define Localization_DEFAULT NULL

#define Timestamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   ts,                1)
#define Timestamp_CALLBACK NULL
#define Timestamp_DEFAULT NULL

#define AnalogChannel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    channel_type,      1) \
X(a, CALLBACK, SINGULAR, BYTES,    encoded_analog_points,   2)
#define AnalogChannel_CALLBACK pb_default_field_callback
#define AnalogChannel_DEFAULT NULL

#define Communication_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    instruction,       1) \
X(a, STATIC,   OPTIONAL, UENUM,    driver_response,   2)
#define Communication_CALLBACK NULL
#define Communication_DEFAULT NULL

#define CarState_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    engine_status,     1) \
X(a, STATIC,   OPTIONAL, BOOL,     rollover_status,   2)
#define CarState_CALLBACK NULL
#define CarState_DEFAULT NULL

#define RTKCorrection_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    rtk_correction,    1)
#define RTKCorrection_CALLBACK pb_default_field_callback
#define RTKCorrection_DEFAULT NULL

#define Observation_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,gps,data.gps),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,localization,data.localization),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,communication,data.communication),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,analog_ch,data.analog_ch),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,car_state,data.car_state),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,rtk_correction,data.rtk_correction),   7)
#define Observation_CALLBACK NULL
#define Observation_DEFAULT NULL
#define Observation_timestamp_MSGTYPE Timestamp
#define Observation_data_gps_MSGTYPE GPS
#define Observation_data_localization_MSGTYPE Localization
#define Observation_data_communication_MSGTYPE Communication
#define Observation_data_analog_ch_MSGTYPE AnalogChannel
#define Observation_data_car_state_MSGTYPE CarState
#define Observation_data_rtk_correction_MSGTYPE RTKCorrection

#define LiveComm_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  observations,      1)
#define LiveComm_CALLBACK pb_default_field_callback
#define LiveComm_DEFAULT NULL
#define LiveComm_observations_MSGTYPE Observation

extern const pb_msgdesc_t GPS_msg;
extern const pb_msgdesc_t Localization_msg;
extern const pb_msgdesc_t Timestamp_msg;
extern const pb_msgdesc_t AnalogChannel_msg;
extern const pb_msgdesc_t Communication_msg;
extern const pb_msgdesc_t CarState_msg;
extern const pb_msgdesc_t RTKCorrection_msg;
extern const pb_msgdesc_t Observation_msg;
extern const pb_msgdesc_t LiveComm_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define GPS_fields &GPS_msg
#define Localization_fields &Localization_msg
#define Timestamp_fields &Timestamp_msg
#define AnalogChannel_fields &AnalogChannel_msg
#define Communication_fields &Communication_msg
#define CarState_fields &CarState_msg
#define RTKCorrection_fields &RTKCorrection_msg
#define Observation_fields &Observation_msg
#define LiveComm_fields &LiveComm_msg

/* Maximum encoded size of messages (where known) */
/* AnalogChannel_size depends on runtime parameters */
/* RTKCorrection_size depends on runtime parameters */
/* Observation_size depends on runtime parameters */
/* LiveComm_size depends on runtime parameters */
#define BAJA_LIVE_COMM_PB_H_MAX_SIZE             Localization_size
#define CarState_size                            4
#define Communication_size                       4
#define GPS_size                                 15
#define Localization_size                        60
#define Timestamp_size                           11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
