/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_BAJA_SAMPLE_PB_H_INCLUDED
#define PB_BAJA_SAMPLE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Single sample with differential timestamp */
typedef struct _Sample {
    uint8_t channel_id; /* ADC channel ID (uint8) */
    uint32_t value; /* Raw ADC value (24-bit) */
    uint16_t timestamp_delta; /* Microseconds since base timestamp (uint16) */
} Sample;

/* Fixed-size batch with differential timestamps */
typedef struct _FixedDataChunk {
    uint64_t base_timestamp; /* Base timestamp in microseconds */
    Sample samples[50];
    uint16_t sample_count; /* Actual number of valid samples (uint16) */
} FixedDataChunk;

/* Verbose batch with full timestamps */
typedef struct _VerboseDataChunk {
    uint64_t timestamps[50];
    uint8_t channel_ids[50];
    uint32_t values[50];
    uint16_t sample_count; /* Actual number of valid samples (uint16) */
} VerboseDataChunk;

/* Master data chunk that can contain either a fixed or verbose chunk */
typedef struct _DataChunk {
    pb_size_t which_chunk_type;
    union {
        FixedDataChunk fixed;
        VerboseDataChunk verbose;
    } chunk_type;
} DataChunk;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Sample_init_default                      {0, 0, 0}
#define FixedDataChunk_init_default              {0, {Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default}, 0}
#define VerboseDataChunk_init_default            {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define DataChunk_init_default                   {0, {FixedDataChunk_init_default}}
#define Sample_init_zero                         {0, 0, 0}
#define FixedDataChunk_init_zero                 {0, {Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero}, 0}
#define VerboseDataChunk_init_zero               {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define DataChunk_init_zero                      {0, {FixedDataChunk_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Sample_channel_id_tag                    1
#define Sample_value_tag                         2
#define Sample_timestamp_delta_tag               3
#define FixedDataChunk_base_timestamp_tag        1
#define FixedDataChunk_samples_tag               2
#define FixedDataChunk_sample_count_tag          3
#define VerboseDataChunk_timestamps_tag          1
#define VerboseDataChunk_channel_ids_tag         2
#define VerboseDataChunk_values_tag              3
#define VerboseDataChunk_sample_count_tag        4
#define DataChunk_fixed_tag                      1
#define DataChunk_verbose_tag                    2

/* Struct field encoding specification for nanopb */
#define Sample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   channel_id,        1) \
X(a, STATIC,   SINGULAR, UINT32,   value,             2) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_delta,   3)
#define Sample_CALLBACK NULL
#define Sample_DEFAULT NULL

#define FixedDataChunk_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED64,  base_timestamp,    1) \
X(a, STATIC,   FIXARRAY, MESSAGE,  samples,           2) \
X(a, STATIC,   SINGULAR, UINT32,   sample_count,      3)
#define FixedDataChunk_CALLBACK NULL
#define FixedDataChunk_DEFAULT NULL
#define FixedDataChunk_samples_MSGTYPE Sample

#define VerboseDataChunk_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, FIXED64,  timestamps,        1) \
X(a, STATIC,   FIXARRAY, UINT32,   channel_ids,       2) \
X(a, STATIC,   FIXARRAY, UINT32,   values,            3) \
X(a, STATIC,   SINGULAR, UINT32,   sample_count,      4)
#define VerboseDataChunk_CALLBACK NULL
#define VerboseDataChunk_DEFAULT NULL

#define DataChunk_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (chunk_type,fixed,chunk_type.fixed),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (chunk_type,verbose,chunk_type.verbose),   2)
#define DataChunk_CALLBACK NULL
#define DataChunk_DEFAULT NULL
#define DataChunk_chunk_type_fixed_MSGTYPE FixedDataChunk
#define DataChunk_chunk_type_verbose_MSGTYPE VerboseDataChunk

extern const pb_msgdesc_t Sample_msg;
extern const pb_msgdesc_t FixedDataChunk_msg;
extern const pb_msgdesc_t VerboseDataChunk_msg;
extern const pb_msgdesc_t DataChunk_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Sample_fields &Sample_msg
#define FixedDataChunk_fields &FixedDataChunk_msg
#define VerboseDataChunk_fields &VerboseDataChunk_msg
#define DataChunk_fields &DataChunk_msg

/* Maximum encoded size of messages (where known) */
#define BAJA_SAMPLE_PB_H_MAX_SIZE                DataChunk_size
#define DataChunk_size                           907
#define FixedDataChunk_size                      763
#define Sample_size                              13
#define VerboseDataChunk_size                    904

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
