/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_KILL_PACKET_PB_H_INCLUDED
#define PB_KILL_PACKET_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _KillPacket {
    uint8_t command;
} KillPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define KillPacket_init_default                  {0}
#define KillPacket_init_zero                     {0}

/* Field tags (for use in manual encoding/decoding) */
#define KillPacket_command_tag                   1

/* Struct field encoding specification for nanopb */
#define KillPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   command,           1)
#define KillPacket_CALLBACK NULL
#define KillPacket_DEFAULT NULL

extern const pb_msgdesc_t KillPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define KillPacket_fields &KillPacket_msg

/* Maximum encoded size of messages (where known) */
#define KILL_PACKET_PB_H_MAX_SIZE                KillPacket_size
#define KillPacket_size                          3

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
