/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TEENSY_DATA_PB_H_INCLUDED
#define PB_TEENSY_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Single sample from the Teensy using the internal channel id. */
typedef struct _Sample {
    uint8_t internal_channel_id; /* internal channel id (0-29) */
    uint32_t value; /* Sensor reading */
    uint16_t timestamp_delta; /* Delta time (in microseconds) */
} Sample;

/* DataChunk message grouping multiple samples. */
typedef struct _DataChunk {
    uint64_t timestamps[50];
    uint8_t internal_channel_ids[50];
    uint32_t values[50];
    uint16_t sample_count; /* Actual number of valid samples */
} DataChunk;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Sample_init_default                      {0, 0, 0}
#define DataChunk_init_default                   {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define Sample_init_zero                         {0, 0, 0}
#define DataChunk_init_zero                      {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Sample_internal_channel_id_tag           1
#define Sample_value_tag                         2
#define Sample_timestamp_delta_tag               3
#define DataChunk_timestamps_tag                 1
#define DataChunk_internal_channel_ids_tag       2
#define DataChunk_values_tag                     3
#define DataChunk_sample_count_tag               4

/* Struct field encoding specification for nanopb */
#define Sample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   internal_channel_id,   1) \
X(a, STATIC,   SINGULAR, UINT32,   value,             2) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_delta,   3)
#define Sample_CALLBACK NULL
#define Sample_DEFAULT NULL

#define DataChunk_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, FIXED64,  timestamps,        1) \
X(a, STATIC,   FIXARRAY, UINT32,   internal_channel_ids,   2) \
X(a, STATIC,   FIXARRAY, UINT32,   values,            3) \
X(a, STATIC,   SINGULAR, UINT32,   sample_count,      4)
#define DataChunk_CALLBACK NULL
#define DataChunk_DEFAULT NULL

extern const pb_msgdesc_t Sample_msg;
extern const pb_msgdesc_t DataChunk_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Sample_fields &Sample_msg
#define DataChunk_fields &DataChunk_msg

/* Maximum encoded size of messages (where known) */
#define DataChunk_size                           904
#define Sample_size                              13
#define TEENSY_DATA_PB_H_MAX_SIZE                DataChunk_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
