/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TEENSY_DATA_PB_H_INCLUDED
#define PB_TEENSY_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Sample {
    uint64_t timestamp;
    uint8_t internal_channel_id;
    uint32_t value;
} Sample;

typedef struct _ChannelSampleBatch {
    pb_size_t samples_count;
    Sample samples[50];
} ChannelSampleBatch;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Sample_init_default                      {0, 0, 0}
#define ChannelSampleBatch_init_default          {0, {Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default, Sample_init_default}}
#define Sample_init_zero                         {0, 0, 0}
#define ChannelSampleBatch_init_zero             {0, {Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero, Sample_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Sample_timestamp_tag                     1
#define Sample_internal_channel_id_tag           2
#define Sample_value_tag                         3
#define ChannelSampleBatch_samples_tag           1

/* Struct field encoding specification for nanopb */
#define Sample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED64,  timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   internal_channel_id,   2) \
X(a, STATIC,   SINGULAR, UINT32,   value,             3)
#define Sample_CALLBACK NULL
#define Sample_DEFAULT NULL

#define ChannelSampleBatch_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  samples,           1)
#define ChannelSampleBatch_CALLBACK NULL
#define ChannelSampleBatch_DEFAULT NULL
#define ChannelSampleBatch_samples_MSGTYPE Sample

extern const pb_msgdesc_t Sample_msg;
extern const pb_msgdesc_t ChannelSampleBatch_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Sample_fields &Sample_msg
#define ChannelSampleBatch_fields &ChannelSampleBatch_msg

/* Maximum encoded size of messages (where known) */
#define ChannelSampleBatch_size                  1000
#define Sample_size                              18
#define TEENSY_DATA_PB_H_MAX_SIZE                ChannelSampleBatch_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
