/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TIME_SYNC_PB_H_INCLUDED
#define PB_TIME_SYNC_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _TimeSync {
    uint64_t time_us;
} TimeSync;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TimeSync_init_default                    {0}
#define TimeSync_init_zero                       {0}

/* Field tags (for use in manual encoding/decoding) */
#define TimeSync_time_us_tag                     1

/* Struct field encoding specification for nanopb */
#define TimeSync_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED64,  time_us,           1)
#define TimeSync_CALLBACK NULL
#define TimeSync_DEFAULT NULL

extern const pb_msgdesc_t TimeSync_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TimeSync_fields &TimeSync_msg

/* Maximum encoded size of messages (where known) */
#define TIME_SYNC_PB_H_MAX_SIZE                  TimeSync_size
#define TimeSync_size                            9

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
