/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_WSG_CAL_COM_PB_H_INCLUDED
#define PB_WSG_CAL_COM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _cal_command_t {
    uint32_t command;
} cal_command_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cal_command_t_init_default               {0}
#define cal_command_t_init_zero                  {0}

/* Field tags (for use in manual encoding/decoding) */
#define cal_command_t_command_tag                1

/* Struct field encoding specification for nanopb */
#define cal_command_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   command,           1)
#define cal_command_t_CALLBACK NULL
#define cal_command_t_DEFAULT NULL

extern const pb_msgdesc_t cal_command_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cal_command_t_fields &cal_command_t_msg

/* Maximum encoded size of messages (where known) */
#define WSG_CAL_COM_PB_H_MAX_SIZE                cal_command_t_size
#define cal_command_t_size                       6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
