/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_WSG_COM_PB_H_INCLUDED
#define PB_WSG_COM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _wsg_com_poll_t {
    char mac_address[18];
} wsg_com_poll_t;

typedef struct _wsg_com_response_t {
    char mac_address[18];
    uint32_t command;
    uint32_t dac_bias;
} wsg_com_response_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define wsg_com_poll_t_init_default              {""}
#define wsg_com_response_t_init_default          {"", 0, 0}
#define wsg_com_poll_t_init_zero                 {""}
#define wsg_com_response_t_init_zero             {"", 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define wsg_com_poll_t_mac_address_tag           1
#define wsg_com_response_t_mac_address_tag       1
#define wsg_com_response_t_command_tag           2
#define wsg_com_response_t_dac_bias_tag          3

/* Struct field encoding specification for nanopb */
#define wsg_com_poll_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   mac_address,       1)
#define wsg_com_poll_t_CALLBACK NULL
#define wsg_com_poll_t_DEFAULT NULL

#define wsg_com_response_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   mac_address,       1) \
X(a, STATIC,   SINGULAR, FIXED32,  command,           2) \
X(a, STATIC,   SINGULAR, FIXED32,  dac_bias,          3)
#define wsg_com_response_t_CALLBACK NULL
#define wsg_com_response_t_DEFAULT NULL

extern const pb_msgdesc_t wsg_com_poll_t_msg;
extern const pb_msgdesc_t wsg_com_response_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wsg_com_poll_t_fields &wsg_com_poll_t_msg
#define wsg_com_response_t_fields &wsg_com_response_t_msg

/* Maximum encoded size of messages (where known) */
#define WSG_COM_PB_H_MAX_SIZE                    wsg_com_response_t_size
#define wsg_com_poll_t_size                      19
#define wsg_com_response_t_size                  29

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
