/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_WSG_PI_TIME_PB_H_INCLUDED
#define PB_WSG_PI_TIME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _wsg_pi_time_t {
    uint64_t time_us;
} wsg_pi_time_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define wsg_pi_time_t_init_default               {0}
#define wsg_pi_time_t_init_zero                  {0}

/* Field tags (for use in manual encoding/decoding) */
#define wsg_pi_time_t_time_us_tag                1

/* Struct field encoding specification for nanopb */
#define wsg_pi_time_t_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED64,  time_us,           1)
#define wsg_pi_time_t_CALLBACK NULL
#define wsg_pi_time_t_DEFAULT NULL

extern const pb_msgdesc_t wsg_pi_time_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wsg_pi_time_t_fields &wsg_pi_time_t_msg

/* Maximum encoded size of messages (where known) */
#define WSG_PI_TIME_PB_H_MAX_SIZE                wsg_pi_time_t_size
#define wsg_pi_time_t_size                       9

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
