/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_WSG_CAL_DATA_PB_H_INCLUDED
#define PB_WSG_CAL_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _wsg_cal_data_t {
    uint32_t adc_value[40];
    uint32_t dac_bias[40];
    float voltage[40];
} wsg_cal_data_t;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define wsg_cal_data_t_init_default              {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define wsg_cal_data_t_init_zero                 {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}

/* Field tags (for use in manual encoding/decoding) */
#define wsg_cal_data_t_adc_value_tag             1
#define wsg_cal_data_t_dac_bias_tag              2
#define wsg_cal_data_t_voltage_tag               3

/* Struct field encoding specification for nanopb */
#define wsg_cal_data_t_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, UINT32,   adc_value,         1) \
X(a, STATIC,   FIXARRAY, UINT32,   dac_bias,          2) \
X(a, STATIC,   FIXARRAY, FLOAT,    voltage,           3)
#define wsg_cal_data_t_CALLBACK NULL
#define wsg_cal_data_t_DEFAULT NULL

extern const pb_msgdesc_t wsg_cal_data_t_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define wsg_cal_data_t_fields &wsg_cal_data_t_msg

/* Maximum encoded size of messages (where known) */
#define WSG_CAL_DATA_PB_H_MAX_SIZE               wsg_cal_data_t_size
#define wsg_cal_data_t_size                      680

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
