/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_WSG_DATA_PB_H_INCLUDED
#define PB_WSG_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _WSG_Data {
    uint8_t id;
    uint32_t bias;
    uint16_t sg_data[3];
    uint64_t timestamp;
} WSG_Data;

typedef struct _WSG_Batch {
    pb_size_t samples_count;
    WSG_Data samples[6];
} WSG_Batch;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define WSG_Data_init_default                    {0, 0, {0, 0, 0}, 0}
#define WSG_Batch_init_default                   {0, {WSG_Data_init_default, WSG_Data_init_default, WSG_Data_init_default, WSG_Data_init_default, WSG_Data_init_default, WSG_Data_init_default}}
#define WSG_Data_init_zero                       {0, 0, {0, 0, 0}, 0}
#define WSG_Batch_init_zero                      {0, {WSG_Data_init_zero, WSG_Data_init_zero, WSG_Data_init_zero, WSG_Data_init_zero, WSG_Data_init_zero, WSG_Data_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define WSG_Data_id_tag                          1
#define WSG_Data_bias_tag                        2
#define WSG_Data_sg_data_tag                     3
#define WSG_Data_timestamp_tag                   4
#define WSG_Batch_samples_tag                    1

/* Struct field encoding specification for nanopb */
#define WSG_Data_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, FIXED32,  bias,              2) \
X(a, STATIC,   FIXARRAY, UINT32,   sg_data,           3) \
X(a, STATIC,   SINGULAR, FIXED64,  timestamp,         4)
#define WSG_Data_CALLBACK NULL
#define WSG_Data_DEFAULT NULL

#define WSG_Batch_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  samples,           1)
#define WSG_Batch_CALLBACK NULL
#define WSG_Batch_DEFAULT NULL
#define WSG_Batch_samples_MSGTYPE WSG_Data

extern const pb_msgdesc_t WSG_Data_msg;
extern const pb_msgdesc_t WSG_Batch_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WSG_Data_fields &WSG_Data_msg
#define WSG_Batch_fields &WSG_Batch_msg

/* Maximum encoded size of messages (where known) */
#define WSG_Batch_size                           186
#define WSG_DATA_PB_H_MAX_SIZE                   WSG_Batch_size
#define WSG_Data_size                            29

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
